### ISSUE TITLE
Length of hash could be determined by timing attack. 

### ISSUE THREAD

**Issue by nv1t** [freewil/scmp#3]
Though it jumps out on different lengths, the length of the string can be determined by a timing attack.

"len" should always be the length of the longer string.
fill up the smaller string with bytes to match the longer string.

Idea:
```javascript
  var len = Math.max(a.length, b.length);

  var result = 0;
  var tmp1,tmp2;
  for (var i = 0; i < len; ++i) {
    tmp1 = a.charCodeAt(i) || 97;
    tmp2 = b.charCodeAt(i) || 97;
    result |= tmp1 ^ tmp2;
  }
```

**Comment by freewil** [comment]
My first thought is that while it would be nice to not expose the possibility of learning the length of the secret string, it shouldn't matter given a sufficiently long enough string.

With that being said:

* I'm not sure what unicode character `97` is - but I don't think we can just default to any value, we have to make sure that the values when xored are not equal in the case of the strings not being the same length
* I also am skeptical that this would actually solve the problem since I suspect that the `||` would increase computation time in a possibly statistically significant way

**Comment by nv1t** [comment]
I agree this is just a minor issue and just a notice for some should keep in mind using it with shorter strings.

First Bullet Point:
why would you make sure the strings are not equal, which you append. 
* case 1 - the secret is shorter: the input string must be the secret+filler
* case 2 - the input is shorter: the secret shouldn't be filler times len(secret)

if you choose the filler to be a non printable character, everything should be fine.

Second Bullet Point: 
About the ||: Jup...haven't thought about the increased computation time. (something to benchmark?)

**Comment by freewil** [comment]
closing this as this module is not meant to address this issue.
